### ISSUE TITLE
Dev setup

### ISSUE THREAD

**Issue by wardbeyens** [benjamintd/chronotrains#13]
How to get data inside the database?

After:

- setting up a db
```
version: "3.8"
services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
```
- fill in .env
- yarn
- yarn postinstall

What do I need to do to get the data?
